version: "2"
services:
  hmrc-redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - hmrc-redis:/data
  hmrc-postgres:
    container_name: postgres
    image: postgres:13.10
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=william
      - POSTGRES_PASSWORD=
      - LANG=C.UTF-8
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_WORK_MEM=32MB
    ports:
      - 5432:5432
    volumes:
      - hmrc-postgres-13:/var/lib/postgresql/data
  hmrc-opensearch:
    container_name: hmrc-opensearch
    image: opensearchproject/opensearch:2
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    environment:
        - bootstrap.memory_lock=true
        - discovery.type=single-node
        - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
        - cluster.routing.allocation.disk.threshold_enabled=false
        - plugins.security.disabled=true
    ulimits:
        memlock:
            soft: -1
            hard: -1
        nofile:
          soft: 65536
          hard: 65536
    healthcheck:
      interval: 60s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
    volumes:
    - hmrc-es:/usr/share/opensearch/data
    - /home/william/Repositories/hmrc/trade-tariff-backend/config/opensearch/synonyms_all.txt:/usr/share/opensearch/config/synonyms_all.txt
    - /home/william/Repositories/hmrc/trade-tariff-backend/config/opensearch/stemming_exclusions_all.txt:/usr/share/opensearch/config/stemming_exclusions_all.txt
    # - /home/william/opensearch.yml:/usr/share/opensearch/config/opensearch.yml

volumes:
  hmrc-redis:
    driver: local
  hmrc-postgres-10:
    driver: local
  hmrc-postgres-13:
    driver: local
  hmrc-mysql-8:
    driver: local
  hmrc-es:
    driver: local
