version: "2"
services:
  hmrc-redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - hmrc-redis:/data
  hmrc-postgres:
    container_name: postgres
    image: postgres:13.10
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=william
      - POSTGRES_PASSWORD=
      - LANG=C.UTF-8
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - hmrc-postgres-13:/var/lib/postgresql/data
  # hmrc-mysql:
  #   container_name: hmrc-mysql
  #   image: mysql:8.0.30
  #   environment:
  #     - MYSQL_DATABASE=signonotron2_development
  #     - MYSQL_USER=signonotron2
  #     - MYSQL_PASSWORD=signonotron2
  #     - MYSQL_ROOT_PASSWORD=
  #     - MYSQL_ALLOW_EMPTY_PASSWORD=true
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - hmrc-mysql-8:/var/lib/mysql
  hmrc-opensearch:
    container_name: hmrc-opensearch
    image: opensearchproject/opensearch:2
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    environment:
        - bootstrap.memory_lock=true
        - discovery.type=single-node
        - "OPENSEARCH_JAVA_OPTS=-Xms8g -Xmx8g"
        - cluster.routing.allocation.disk.threshold_enabled=false
        - plugins.security.disabled=true
    ulimits:
        memlock:
            soft: -1
            hard: -1
        nofile:
          soft: 65536
          hard: 65536
    healthcheck:
      interval: 60s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
    volumes:
    - hmrc-es:/usr/share/opensearch/data
    - /home/william/Repositories/hmrc/trade-tariff-backend/config/opensearch/synonyms_all.txt:/usr/share/opensearch/config/synonyms_all.txt
    - /home/william/Repositories/hmrc/trade-tariff-backend/config/opensearch/stemming_exclusions_all.txt:/usr/share/opensearch/config/stemming_exclusions_all.txt
  # hmrc-kibana:
  #   container_name: hmrc-kibana
  #   image: kibana:7.9.3
  #   ports:
  #     - 5601:5601
  #   environment:
  #     ELASTICSEARCH_URL: https://prod-lon-f7f9d603-d3ae-4eb5-be0c-1ac4e7a23103-paas-cf-prod.aivencloud.com:19676
  #     ELASTICSEARCH_HOSTS: https://prod-lon-f7f9d603-d3ae-4eb5-be0c-1ac4e7a23103-paas-cf-prod.aivencloud.com:19676
  #     ELASTICSEARCH_USERNAME: 384689a1-8a42-4e95-b028-9403ac7b320b
  #     ELASTICSEARCH_PASSWORD: xy4st802kmvq80co

volumes:
  hmrc-redis:
    driver: local
  hmrc-postgres-10:
    driver: local
  hmrc-postgres-13:
    driver: local
  hmrc-mysql-8:
    driver: local
  hmrc-es:
    driver: local
